name: Generate Pacman Contribution Graph

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: AdanChain
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Commit & push only if changed
        uses: EndBug/add-and-commit@v9
        with:
          message: "ðŸ”„ Update Pacman contribution graph"
          add: "output"
          default_author: github_actions
          push: true
          pull: '--rebase --autostash'
